# Generated by Django 4.2.2 on 2023-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='area',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='area',
            name='nombreArea',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
