# Generated by Django 4.2.2 on 2023-06-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0002_remove_area_horas_remove_area_pacientes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='TurnoTrabajo',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='area',
            new_name='turno',
        ),
        migrations.RenameField(
            model_name='turnotrabajo',
            old_name='nombreArea',
            new_name='turno',
        ),
    ]
