# Generated by Django 4.2.2 on 2023-07-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0003_rename_area_turnotrabajo_rename_area_doctor_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar_Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctores.lugar_trabajo'),
        ),
    ]
